name: Profiles validation

on:
  pull_request:
    branches:
      - master

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate profiles
        run: npx ajv-cli -s ci/profiles-schema.json -d "validators/**/profile.json" | grep -v " valid"
